/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRatingsRouteImport } from './routes/_app.ratings'
import { Route as AppOpportunitiesRouteImport } from './routes/_app.opportunities'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app.opportunities.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminQuestionsRouteImport } from './routes/_app.admin.questions'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRatingsRoute = AppRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOpportunitiesRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuestionsRoute = AppAdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/ratings': typeof AppRatingsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/ratings': typeof AppRatingsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/_app/ratings': typeof AppRatingsRoute
  '/_app/admin/questions': typeof AppAdminQuestionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/dashboard'
    | '/opportunities'
    | '/ratings'
    | '/admin/questions'
    | '/admin/users'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/dashboard'
    | '/opportunities'
    | '/ratings'
    | '/admin/questions'
    | '/admin/users'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pending'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/opportunities'
    | '/_app/ratings'
    | '/_app/admin/questions'
    | '/_app/admin/users'
    | '/_app/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ratings': {
      id: '/_app/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AppRatingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppOpportunitiesRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/questions': {
      id: '/_app/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AppAdminQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppOpportunitiesRouteChildren {
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
}

const AppOpportunitiesRouteChildren: AppOpportunitiesRouteChildren = {
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
}

const AppOpportunitiesRouteWithChildren =
  AppOpportunitiesRoute._addFileChildren(AppOpportunitiesRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRouteWithChildren
  AppRatingsRoute: typeof AppRatingsRoute
  AppAdminQuestionsRoute: typeof AppAdminQuestionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOpportunitiesRoute: AppOpportunitiesRouteWithChildren,
  AppRatingsRoute: AppRatingsRoute,
  AppAdminQuestionsRoute: AppAdminQuestionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
