/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRatingsRouteImport } from './routes/_app.ratings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOpportunitiesIndexRouteImport } from './routes/_app.opportunities.index'
import { Route as AppGoalsIndexRouteImport } from './routes/_app.goals.index'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app.opportunities.$id'
import { Route as AppGoalsScopeRouteImport } from './routes/_app.goals.$scope'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminQuestionsRouteImport } from './routes/_app.admin.questions'
import { Route as AppGoalsArchitectsUserIdRouteImport } from './routes/_app.goals.architects.$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRatingsRoute = AppRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIndexRoute = AppOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsScopeRoute = AppGoalsScopeRouteImport.update({
  id: '/goals/$scope',
  path: '/goals/$scope',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuestionsRoute = AppAdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsArchitectsUserIdRoute =
  AppGoalsArchitectsUserIdRouteImport.update({
    id: '/goals/architects/$userId',
    path: '/goals/architects/$userId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/ratings': typeof AppRatingsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/goals/$scope': typeof AppGoalsScopeRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/opportunities/': typeof AppOpportunitiesIndexRoute
  '/goals/architects/$userId': typeof AppGoalsArchitectsUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/ratings': typeof AppRatingsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/goals/$scope': typeof AppGoalsScopeRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/goals': typeof AppGoalsIndexRoute
  '/opportunities': typeof AppOpportunitiesIndexRoute
  '/goals/architects/$userId': typeof AppGoalsArchitectsUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ratings': typeof AppRatingsRoute
  '/_app/admin/questions': typeof AppAdminQuestionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/goals/$scope': typeof AppGoalsScopeRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/opportunities/': typeof AppOpportunitiesIndexRoute
  '/_app/goals/architects/$userId': typeof AppGoalsArchitectsUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/ratings'
    | '/admin/questions'
    | '/admin/users'
    | '/goals/$scope'
    | '/opportunities/$id'
    | '/goals/'
    | '/opportunities/'
    | '/goals/architects/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/ratings'
    | '/admin/questions'
    | '/admin/users'
    | '/goals/$scope'
    | '/opportunities/$id'
    | '/goals'
    | '/opportunities'
    | '/goals/architects/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/pending'
    | '/reset-password'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/ratings'
    | '/_app/admin/questions'
    | '/_app/admin/users'
    | '/_app/goals/$scope'
    | '/_app/opportunities/$id'
    | '/_app/goals/'
    | '/_app/opportunities/'
    | '/_app/goals/architects/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ratings': {
      id: '/_app/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AppRatingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/': {
      id: '/_app/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AppOpportunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/$scope': {
      id: '/_app/goals/$scope'
      path: '/goals/$scope'
      fullPath: '/goals/$scope'
      preLoaderRoute: typeof AppGoalsScopeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/questions': {
      id: '/_app/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AppAdminQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/architects/$userId': {
      id: '/_app/goals/architects/$userId'
      path: '/goals/architects/$userId'
      fullPath: '/goals/architects/$userId'
      preLoaderRoute: typeof AppGoalsArchitectsUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppRatingsRoute: typeof AppRatingsRoute
  AppAdminQuestionsRoute: typeof AppAdminQuestionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppGoalsScopeRoute: typeof AppGoalsScopeRoute
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppOpportunitiesIndexRoute: typeof AppOpportunitiesIndexRoute
  AppGoalsArchitectsUserIdRoute: typeof AppGoalsArchitectsUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppRatingsRoute: AppRatingsRoute,
  AppAdminQuestionsRoute: AppAdminQuestionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppGoalsScopeRoute: AppGoalsScopeRoute,
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppOpportunitiesIndexRoute: AppOpportunitiesIndexRoute,
  AppGoalsArchitectsUserIdRoute: AppGoalsArchitectsUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
